---
title: "Documentation Bellabeat project"
author: "Maciej Broda"
date: "2025-03-05"
output:
  html_document:
    df_print: paged
---

## About this documentation

I created this documentation to showcase my thought process when working with data during a project, rather than to produce a formal report. Treat this file as an addition to my skills showcase. Thank you and enjoy.

## Business problem

Sršen asks you to analyze smart device usage data in order to gain insight into how consumers use non-Bellabeat smart
devices. She then wants you to select one Bellabeat product to apply these insights to in your presentation.

## Aim of the project

I need to prepare, clean, analyze, share, and act on the data to identify trends in other non-Bella high-tech smart products. After that, I will choose one of these products to provide detailed insights. This approach should help Sršen understand how users of non-Bella devices interact with their products.

## Prepare data 

I fetched data from Kaggle's "FitBit Fitness Tracker Data". I reviewed all the tables and found them consistent in format. Although the data is not the newest—since the information is from 2016—we can still extract many insights for our stakeholder. The last update was about a year ago, so I assume the database is maintained properly and updated annually. The database does not contain any sensitive user data, so privacy is not an issue. Since the database is released under CC0: Public Domain, I can use it without any additional permissions. As I fetched the original data from Kaggle and the original is always available online, I did not make copies of the downloaded tables. I would like to include the table weightLogInfo.csv, but unfortunately it does not have enough records to be as reliable as dailyActivity_merged.csv. Instead, I will include sleepDay_merged.csv to analyze trends between active sleep time and calories burned.

## Process data

It was time to clean the data, find errors, and transform it into a consistent format. I preferred to use SQL Server instead of Excel, because the dataset contains many records, making SQL a more efficient tool for data cleaning. I attempted to add the dailyActivity_merge table to SSMS with auto-detection of column data types, but encountered an error: "Input string was not in a correct format. (mscorlib)". Consequently, I imported all columns as nvarchar(50) and then altered them manually. My SQL code is located in the DataPrepering.sql file in the project folder, which details the step-by-step process.

Summary of the data processing:

* Parsed all columns to proper data type for analyse phase
* Searched for null values in data
* Searched for and deleted outliers 

## Analyze data

First, I analyzed the correlation between average total steps and average calories burned using SQL, but I did not find a clear pattern indicating a trend between the two. The same was true for the correlation between average total time in bed and average calories burned. Additionally, I couldn’t analyze any trends for weight due to insufficient data.

To determine the correlation between different intensities of exercise, I used R. I loaded the data from my cleaned DailyActivityCleaned.csv file into R and then used the cor function to calculate correlations for very active, fairly active, and lightly active minutes.

Results of Pearson correlation analysis:

* Very active minutes & Calories burned = 0.61
* Fairly active minutes & Calories burned = 0.26
* Lightly active minutes & Calories burned = 0.14
* Sedentary minutes & Calories burned = -0.05

Based on these results, we can conclude that very active minutes have the highest impact on calorie burn. I plan to focus on this aspect and create a scatter plot to provide clear insights for Sršen. The comprehensive analysis is detailed in the DataPrepering.sql file.

## Visualization 

I created visualizations in Tableau. I developed three scatter plots to illustrate the differences and to show which factors influence calorie burning the most. In the presentation, I focused on simplicity and on highlighting the most important data for the stakeholders.

## Summary

Based on the visualizations, a clear correlation emerges: the more time users spend in very active exercises, the higher the calories burned. This insight suggests that focusing marketing efforts on promoting high-intensity workouts can enhance the effectiveness of Bellabeat products and boost customer satisfaction.

